export const timesheets = [
  {
    week: 1,
    date: "1 - 5 January, 2024",
    hours: 40,
    entries: [
      { day: "Monday",    taskName: "UI Design",       projectName: "Project A", taskDescription: "Designed the login page",        hours: 8 },
      { day: "Tuesday",   taskName: "API Integration", projectName: "Project A", taskDescription: "Integrated auth endpoints",      hours: 8 },
      { day: "Wednesday", taskName: "Code Review",     projectName: "Project B", taskDescription: "Reviewed PR for dashboard",      hours: 8 },
      { day: "Thursday",  taskName: "Bug Fix",         projectName: "Project A", taskDescription: "Fixed form validation issues",   hours: 8 },
      { day: "Friday",    taskName: "Testing",         projectName: "Project B", taskDescription: "Wrote unit tests for auth flow", hours: 8 },
    ],
  },
  {
    week: 2,
    date: "8 - 12 January, 2024",
    hours: 20,
    entries: [
      { day: "Monday",    taskName: "Planning",      projectName: "Project B", taskDescription: "Sprint planning meeting",      hours: 8 },
      { day: "Tuesday",   taskName: "UI Design",     projectName: "Project A", taskDescription: "Designed dashboard layout",   hours: 8 },
      { day: "Wednesday", taskName: "Sick Leave",    projectName: "-",         taskDescription: "Sick leave",                  hours: 0 },
      { day: "Thursday",  taskName: "Sick Leave",    projectName: "-",         taskDescription: "Sick leave",                  hours: 0 },
      { day: "Friday",    taskName: "Documentation", projectName: "Project A", taskDescription: "Wrote API documentation",     hours: 4 },
    ],
  },
  {
    week: 3,
    date: "15 - 19 January, 2024",
    hours: 0,
    entries: [
      { day: "Monday",    taskName: "Leave", projectName: "-", taskDescription: "Annual leave", hours: 0 },
      { day: "Tuesday",   taskName: "Leave", projectName: "-", taskDescription: "Annual leave", hours: 0 },
      { day: "Wednesday", taskName: "Leave", projectName: "-", taskDescription: "Annual leave", hours: 0 },
      { day: "Thursday",  taskName: "Leave", projectName: "-", taskDescription: "Annual leave", hours: 0 },
      { day: "Friday",    taskName: "Leave", projectName: "-", taskDescription: "Annual leave", hours: 0 },
    ],
  },
  { week: 4,  date: "22 - 26 January, 2024",          hours: 40, entries: [] },
  { week: 5,  date: "28 January - 1 February, 2024",  hours: 20, entries: [] },
  { week: 6,  date: "5 - 9 February, 2024",           hours: 40, entries: [] },
  { week: 7,  date: "12 - 16 February, 2024",         hours: 0,  entries: [] },
  { week: 8,  date: "19 - 23 February, 2024",         hours: 40, entries: [] },
  { week: 9,  date: "26 February - 1 March, 2024",    hours: 0,  entries: [] },
  { week: 10, date: "4 - 8 March, 2024",              hours: 40, entries: [] },
  { week: 11, date: "11 - 15 March, 2024",            hours: 0,  entries: [] },
  { week: 12, date: "18 - 22 March, 2024",            hours: 40, entries: [] },
  { week: 13, date: "25 - 29 March, 2024",            hours: 0,  entries: [] },
  { week: 14, date: "1 - 5 April, 2024",              hours: 40, entries: [] },
  { week: 15, date: "8 - 12 April, 2024",             hours: 0,  entries: [] },
  { week: 16, date: "15 - 19 April, 2024",            hours: 40, entries: [] },
  { week: 17, date: "22 - 26 April, 2024",            hours: 0,  entries: [] },
  { week: 18, date: "29 April - 3 May, 2024",         hours: 40, entries: [] },
  { week: 19, date: "6 - 10 May, 2024",               hours: 0,  entries: [] },
  { week: 20, date: "13 - 17 May, 2024",              hours: 40, entries: [] },
  { week: 21, date: "20 - 24 May, 2024",              hours: 0,  entries: [] },
  { week: 22, date: "27 - 31 May, 2024",              hours: 40, entries: [] },
  { week: 23, date: "3 - 7 June, 2024",               hours: 0,  entries: [] },
  { week: 24, date: "10 - 14 June, 2024",             hours: 40, entries: [] },
  { week: 25, date: "17 - 21 June, 2024",             hours: 0,  entries: [] },
];